version: "3.8"
services:
  runner:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file: .env
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '0.35'
          memory: 1GB
        reservations:
          cpus: '0.25'
          memory: 128M


